

SUPABASE_URL = "https://fvzqnjgkwulqunxopwmf.supabase.co"
SUPABASE_KEY = "sb_publishable_Epk_7j7pW8ks0mpRNLZ7cA_JzdP9nb2"
SENHA_TIME = "123" 

MENINAS_DO_TIME = [
    "curupira", "lela", "nicolle", "proerd", "parca", "ganso", 
    "mestica", "md", "sofia", "buh", "sauva", 
    "pelota", "prikita", "arritmia", "maritaca", "carreta", 
    "clt", "maju", "jenga"
]

ISENTAS = ["lela","parca"]